---
title: "Codebook"
author: "Iair_Linker"
date: "Sunday, June 21, 2015"
output: html_document
---

#Data Source 

Original data: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
Original description of the dataset: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

#Dataset Information

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

#Files in the Dataset

The dataset includes the following files:

'README.txt'

'features_info.txt': Shows information about the variables used on the feature vector.

'features.txt': List of all features.

'activity_labels.txt': Links the class labels with their activity name.

'train/X_train.txt': Training set.

'train/y_train.txt': Training labels.

'test/X_test.txt': Test set.

'test/y_test.txt': Test labels.

The following files are available for the train and test data. Their descriptions are equivalent.

'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.

'train/Inertial Signals/total_acc_x_train.txt': The acceleration signal from the smartphone accelerometer X axis in standard gravity units 'g'. Every row shows a 128 element vector. The same description applies for the 'total_acc_x_train.txt' and 'total_acc_z_train.txt' files for the Y and Z axis.

'train/Inertial Signals/body_acc_x_train.txt': The body acceleration signal obtained by subtracting the gravity from the total acceleration.

'train/Inertial Signals/body_gyro_x_train.txt': The angular velocity vector measured by the gyroscope for each window sample. The units are radians/second.



#To achieve the goals i did the following steps:

1.Calls the pachages needed to the assignment: plyr,dplyr, data.table and reshape2. Then i got the the data from train and test data sets in variables to use it in R.

2.-Add the variable name to the head of the test and train x data from the features.

3.Extracts only the measurements on the mean and standard deviation for train and test datasets, achieving the point two of the evaluation.

4.Create the diccionary for the activity of every observation using the join function.

5.Join the activity data with the data of the mesures that i had already create usign the cbind function.

6.-Join the identification of the person with the observations usign the cbind function.

7.-Merge the test(above) with the training(under) sets to create the data. After doing this part, the task four of the evaluation is achieved.

8.-Change the variable names creating descriptive variable names following the instructions in the lectures:all lower case when possible,not duplicated and not have underscores or dot or white spaces. Also,i changed the "t" for "time",the "f" for "frequency",the "Acc" for "accelerator", the "Mag" for magnitude and the "Gyro" for "Gyroscope".
I did not make the names more descriptive becouse i think the variable names would be too long, and you can go to the codebook for the description of every variable.

9.-I created independent tidy data set with the average of each variable for each activity and each subject using the function lapply and by with the data.table package.

If you want to test the tidy data you can create a csv file and open it in a excel sheet 
with this code: write.csv(tidy_data, file = "tidy_data.csv", row.names = FALSE)

If you want to test that the headers are not in the values part of the data set you can compare this: 
        head(data_set[2948,1:3]) and head(train_data[1,1:3]) 
wich shows you the 2948 row of the data sets is the values of the first row of the train data, so thats probe it is ok. Also you can make the sum of thedimensions as a validation.

This way of get the data achieves the point 3 of the evalution:Uses descriptive activity names to name the activities in the data set gives us descriptive activity names for the activities in the data set. You can validate that running this code: unique(data_set[,2])
wich gives you the six activities:WALKING,WALKING_UPSTAIRS,WALKING_DOWNSTAIRS,SITTING, STANDING, LAYING

